import { video } from "framer-motion/client";

const Data = [
  {
    id: 1,
    name: 'Coolie',
    image: 'https://www.wallsnapy.com/img_gallery/coolie-movie-rajini--poster-4k-download-9445507.jpg',
    videoUrl:'https://youtu.be/qeVfT2iLiu0?si=cXKTJV1KI4t4GUpn',
    videoUrl1:'https://youtu.be/OXHTlMPbX7o?list=RDOXHTlMPbX7o',
    videoUrl2:'https://youtu.be/2qCpY38ompo?si=N9N74ecct2W99oAQ',
    videoUrl3:'https://youtu.be/rsJ-LGpE7Lc?si=V1DSFM7f-HdA5qK6',   
     videoUrl4:'https://youtu.be/XPeGLq3MACI?si=e3EAnX7OHD5BrqKn',
      videoUrl5:'https://youtu.be/B6A0A0VJKK8?si=hezQB0H9lYTRqajT',

    description: 'Coolie unleashes Rajinikanth in a high-octane Tamil thriller helmed by Lokesh Kanagaraj.',
    director: 'Lokesh Kanagaraj',
    cast: [
      { id: 1, name: 'Rajinikanth ' },
      { id: 2, name: 'Shuruthi Hasan ' },
      { id: 3, name: 'Naga Arjun ' },
      { id: 4, name: 'Soubin Sahir ' },
      { id: 5, name: 'Sathyaraj  ' },
      { id: 5, name: 'Uppendra  ' },
      { id: 6, name:'Amir khan ' },

    ],
    book:'https://in.bookmyshow.com/movies/chennai/coolie/ET00395817',
    ott:'Null',
    directors: [{ id: 1, name: 'Lokesh Kanagaraj' }],
    genres: [{ id: 1, name: 'Action Drama' }],
    rating: '8.5',
    releaseDate: '2025-08-14',
    runtime: 145,
    popularity: 92.3,
    votes: 12000,
    revenue: '$120M',
    budget: '$30M',
    homepage: 'https://coolie.movie'
  },
  {
  id: 2,
  name: 'Vikram',
  image: 'https://tse4.mm.bing.net/th/id/OIP._Vd7yA0EN7tv8300pRZvjgHaLP?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
   videoUrl:'https://youtu.be/OKBMCL-frPU?si=uWHPiU_UI0nHJB18',
    videoUrl1:'https://youtu.be/OsLCY3vz3t8?si=u25Sc32izvK-9uG6',
    videoUrl2:'https://youtu.be/l_ddxKWNZqI?si=b8XXryBLCvHEhSDW',
    videoUrl3:'https://youtu.be/B789Cx9CpaY?si=d21-3HxJ85hsL3N9',   
     videoUrl4:'https://youtu.be/aoi11BdfpoM?si=z0Dt0leXl5TIvva1',
      videoUrl5:'https://youtu.be/IxDvpoCmAaY?si=j00n4dO170gEqn-X',
  description: 'A gritty action thriller where a retired agent leads a covert mission to eliminate a drug syndicate.',
  director: 'Lokesh Kanagaraj',
  ottplatform:"Hotstar",
  ott:"https://www.hotstar.com/in/movies/vikram/1260106598?search_query=vikra",
  cast: [
    { id: 1, name: 'Kamal Haasan' },
    { id: 2, name: 'Vijay Sethupathi' },
    { id: 3, name: 'Fahadh Faasil' },
    { id: 4, name: 'Narain' },
    { id: 5, name: 'Suriya (cameo)' }
  ],
  directors: [{ id: 1, name: 'Lokesh Kanagaraj' }],
  genres: [{ id: 1, name: 'Action' }, { id: 2, name: 'Thriller' }],
  rating: '8.4',
  releaseDate: '2022-06-03',
  runtime: 173,
  popularity: 94.2,
  votes: 25000,
  revenue: '₹426 crore',
  budget: '₹120 crore',
  homepage: 'https://www.imdb.com/title/tt11934846/'
}
,
  {
  id: 3,
  name: 'The Dark Knight',
  image: 'https://tse2.mm.bing.net/th/id/OIP.iJ0B4QHWW_LdN-wEoTAQLAHaLH?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
ott:"https://www.hotstar.com/in/movies/vikram/1260106598?search_query=vikra",
  description: 'Batman faces the Joker, a criminal mastermind who plunges Gotham into chaos.',
  director: 'Christopher Nolan',
   videoUrl:'https://youtu.be/EXeTwQWrcwY?si=F7AgzZyoJpuTzyck',
    videoUrl1:'https://youtu.be/w1B3Mgklfd0?si=rfA-m-rU-Mf8_RGt',
    videoUrl2:'https://youtu.be/Fs7FIJHLD48?si=CV7YAm-dgsnsORsm',
    videoUrl3:'https://youtu.be/QBHSYkDwNIc?si=yhMxj-GGDJGs3O05',   
     videoUrl4:'https://youtu.be/iGx5a1ifSDs?si=ULTcXJArCXKcBMW4',
      videoUrl5:'https://youtu.be/KwrTczo9PXE?si=E_oHg4Use1BJ2DPx',
  cast: [
    { id: 1, name: 'Christian Bale' },
    { id: 2, name: 'Heath Ledger' }
  ],
  directors: [{ id: 1, name: 'Christopher Nolan' }],
  genres: [{ id: 1, name: 'Action' }, { id: 2, name: 'Crime' }],
  rating: '9.1',
  releaseDate: '2008-07-18',
  runtime: 152,
  popularity: 99.2,
  votes: 2300000,
  revenue: '$1.009B',
  budget: '$185M',
  homepage: 'https://www.warnerbros.com/movies/dark-knight',
  
},
{
  id: 4,
  name: 'Master',
  image: 'https://image.tmdb.org/t/p/original/wjbOlovDadOdPKkSAMohLCjbIsc.jpg',
  description: 'An alcoholic professor is sent to a juvenile home, where he clashes with a ruthless gangster.',
   videoUrl:'https://youtu.be/1_iUFT3nWHk?si=oShQmm-TtDtz3YtD',
    videoUrl1:'https://youtu.be/jIVjWFOY6r4?si=109PM0bzv0GhJFZ-',
    videoUrl2:'https://youtu.be/fRD_3vJagxk?si=lelH3CwvpR8ymfQu',
    videoUrl3:'https://youtu.be/xjM-X-13NYM?si=t0wzjFKzsqmGyAd4',   
     videoUrl4:'https://youtu.be/9m4bEm8YmZs?si=ND3hfTYYQwRF9nUT',
      videoUrl5:'https://youtu.be/V-ta91nrJqQ?si=H_kh6xFa5WZV69MT',
      ott:"https://www.hotstar.com/in/movies/vikram/1260106598?search_query=vikra",
  director: 'Lokesh Kanagaraj',
  cast: [
    { id: 1, name: 'Vijay' },
    { id: 2, name: 'Vijay Sethupathi' },
    { id: 3, name: 'Malavika Mohanan' },
    { id: 4, name: 'Arjun Das' },
    { id: 5, name: 'Mahendran' },
    { id: 6, name: 'Shanthanu Bhagyaraj' },
    { id: 7, name: 'Andrea Jeremiah' },
  ],
  directors: [{ id: 1, name: 'Lokesh Kanagaraj' }],
  genres: [{ id: 1, name: 'Action' }, { id: 2, name: 'Thriller' }],
  rating: '8.0',
  releaseDate: '2021-01-13',
  runtime: 179,
  popularity: 95.5,
  votes: 120000,
  revenue: '$300M',
  budget: '$135M',
  homepage: 'https://www.amazon.com/Master-Tamil/dp/B08VJ8ZJZK'
},
{
  id: 5,
  name: 'Spider-Man: Homecoming',
  image: 'https://www.sonypictures.co.uk/sites/unitedkingdom/files/2020-12/spider_man_homecoming_rating_0.jpg',
  description: 'Peter Parker balances high school life with being Spider-Man while facing the Vulture.',
   videoUrl:'https://youtu.be/rk-dF1lIbIg?si=y6Qt8n0LuaT6mkf7',
    videoUrl1:'https://youtu.be/a6FExz2ycP4?si=UHpqhkLx_J-x1R08',
    videoUrl2:'https://youtu.be/oWBrkwXj8Kg?si=lTVJzS10cCxKO4Gw',
    videoUrl3:'https://youtu.be/PeX8TkHN6mE?si=OxmVVfxUwERaeyIP',   
     videoUrl4:'https://youtu.be/I42Y1bl5uXs?si=VYnud3Y6s3n39959',
      videoUrl5:'https://youtu.be/hecQF7fbjnw?si=1RoTBTihEKO1nv0G',
      ott:"https://www.hotstar.com/in/movies/vikram/1260106598?search_query=vikra",
  director: 'Jon Watts',
  cast: [
    { id: 1, name: 'Tom Holland' },
    { id: 2, name: 'Michael Keaton' }
  ],
  directors: [{ id: 1, name: 'Jon Watts' }],
  genres: [{ id: 1, name: 'Superhero' }, { id: 2, name: 'Adventure' }],
  rating: '7.4',
  releaseDate: '2017-07-07',
  runtime: 133,
  popularity: 94.3,
  votes: 760000,
  revenue: '$880.9M',
  budget: '$175M',
  homepage: 'https://www.marvel.com/movies/spider-man-homecoming'
},
{
  id: 6,
  name: 'Vettaiyan',
  image: 'https://tse4.mm.bing.net/th/id/OIP.Uk9t9Cg3J5GLP_ARyOKNWAHaLP?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
  description: 'A retired cop is pulled back into action to confront a powerful enemy threatening national security.',
   videoUrl:'https://youtu.be/zPqMbwmGC1U?si=88P0j6pm6S8HkM6U',
    videoUrl1:'https://youtu.be/lIwhaTfqwzc?si=Qob_T9D7CiBbjb40',
    videoUrl2:'https://youtu.be/-gb5ZB5Pe0s?si=beWNQS3CjM0a13o3',
    videoUrl3:'https://youtu.be/pmCxMGSKMp4?si=4Qu6mMt_vrkBDbzY',   
     videoUrl4:'https://youtu.be/Qds5tztmb5g?si=n8-W1dq5ltbNE3CA',
      videoUrl5:'https://youtu.be/5WsUIeNAtbM?si=U5D8m4Cwut2qzngJ',
      ott:"https://www.hotstar.com/in/movies/vikram/1260106598?search_query=vikra",
  director: 'T. J. Gnanavel',
  cast: [
    { id: 1, name: 'Rajinikanth' },
    { id: 2, name: 'Amitabh Bachchan' }
  ],
  directors: [{ id: 1, name: 'T. J. Gnanavel' }],
  genres: [{ id: 1, name: 'Action' }, { id: 2, name: 'Drama' }],
  rating: '8.9',
  releaseDate: '2024-10-10',
  runtime: 160,
  popularity: 97.5,
  votes: 150000,
  revenue: '$320M',
  budget: '$100M',
  homepage: ''
},
{
  id: 7,
  name: 'Amaran',
  image: 'https://image.tmdb.org/t/p/original/bsUy2Cc2M5Cl7M84AzrMnsoG0Yt.jpg',
  description: 'A fearless revolutionary rises against corruption and injustice in a gripping political thriller.',
   videoUrl:'https://youtu.be/hylIXfZeB4c?si=mMvhFr7lhzFYH3bE',
    videoUrl1:'https://youtu.be/uLfzcMceO1A?si=h4M8CFYnXbZLPK9l',
    videoUrl2:'https://youtu.be/OIRWdkPMrh0?si=p6x3SJAQer5cphRL',
    videoUrl3:'https://youtu.be/uEXtWevxn-E?si=TxkOLsxK2REu7k6M',   
     videoUrl4:'https://youtu.be/2g9zQp0jruM?si=QKf59dQz_qm5-f2Y',
      videoUrl5:'https://youtu.be/AY3Yea6hBbI?si=DOUEc-oJTbWsZjn6',
      ott:"https://www.hotstar.com/in/movies/vikram/1260106598?search_query=vikra",
  director: 'Rajkumar Periyasamy',
  cast: [
    { id: 1, name: 'Sivakarthikeyan' },
    { id: 2, name: 'Sai Pallavi' }
  ],
  directors: [{ id: 1, name: 'Rajkumar Periyasamy' }],
  genres: [{ id: 1, name: 'Political' }, { id: 2, name: 'Thriller' }],
  rating: '8.7',
  releaseDate: '2024-08-15',
  runtime: 145,
  popularity: 93.2,
  votes: 90000,
  revenue: '$210M',
  budget: '$70M',
  homepage: ''
},
{
  id: 8,
  name: 'Lubber Pandhu',
  image: 'https://m.media-amazon.com/images/M/MV5BNDk0NzM3ZGQtNjk5Mi00Y2I4LWIwYzUtYjA2NzJiNmQyNDdlXkEyXkFqcGc@._V1_.jpg',
  description: 'A young cricketer battles personal demons and societal pressure to chase his dream.',
   videoUrl:'https://youtu.be/oP88LHBukW8?si=IU7U64ZrJU9ZezOk',
    videoUrl1:'https://youtu.be/Bk37oFA_jKs?si=9QKVFQCG9xQMZ2o8',
    videoUrl2:'https://youtu.be/TPVT-LWvgZQ?si=UIEMqqN6hwRo0Na4',
    videoUrl3:'https://youtu.be/-XANQcLQGu4?si=Gxy06TSXsGF7fEec',   
     videoUrl4:'https://youtu.be/dvWdFMCC1-I?si=K2_hNs8wAux5OQOT',
      videoUrl5:'https://youtu.be/Sb9Ng1S92hA?si=3tt-6DhOvUJfsKyE',
      ott:"https://www.hotstar.com/in/movies/vikram/1260106598?search_query=vikra",
  director: 'Tamizharasan Pachamuthu',
  cast: [
    { id: 1, name: 'Harish Kalyan' },
    { id: 2, name: 'Swasika Vijay' }
  ],
  directors: [{ id: 1, name: 'Tamizharasan Pachamuthu' }],
  genres: [{ id: 1, name: 'Sports' }, { id: 2, name: 'Drama' }],
  rating: '7.8',
  releaseDate: '2024-06-21',
  runtime: 138,
  popularity: 88.4,
  votes: 45000,
  revenue: '$60M',
  budget: '$20M',
  homepage: ''
},
{
  id: 9,
  name: 'Mankatha',
  image: 'https://images-na.ssl-images-amazon.com/images/S/pv-target-images/024a4bcf14d5619ada417c20ac128b23dfcc12b52c35423392808f7fa462f0ea._RI_V_TTW_.jpg',
  description: 'A suspended cop leads a gang to rob illegal betting money, but betrayal lurks at every turn.',
   videoUrl:'https://youtu.be/vHESM8iR1JE?si=SAME1roqpe2mMaNo',
    videoUrl1:'https://youtu.be/68ixlbMQaY0?si=jKF1Xdd1PXx_fIeK',
    videoUrl2:'https://youtu.be/fhdLTvl9a74?si=5jbZyN7NM4ruF2Wh',
    videoUrl3:'https://youtu.be/TAv0fApr1js?si=qR6dh1fB-iAXZXer',   
     videoUrl4:'https://youtu.be/r7MlejG7WsI?si=xGTFppAf2K2dF4QE',
      videoUrl5:'https://youtu.be/hc7juCcBPFI?si=BEXQkynlnQJQKb34',
      ott:"https://www.hotstar.com/in/movies/vikram/1260106598?search_query=vikra",
  director: 'Venkat Prabhu',
  cast: [
    { id: 1, name: 'Ajith Kumar' },
    { id: 2, name: 'Arjun Sarja' },
    {id:3, name: 'Trisha'}
  ],
  directors: [{ id: 1, name: 'Venkat Prabhu' }],
  genres: [{ id: 1, name: 'Action' }, { id: 2, name: 'Crime' }],
  rating: '8.2',
  releaseDate: '2011-08-31',
  runtime: 160,
  popularity: 91.3,
  votes: 110000,
  revenue: '$90M',
  budget: '$25M',
  homepage: ''
},
{
  id: 10,
  name: 'Avengers: Endgame',
  image: 'https://upload.wikimedia.org/wikipedia/en/0/0d/Avengers_Endgame_poster.jpg',
  description: 'The Avengers assemble once more to reverse Thanos’s destruction and restore balance to the universe.',
   videoUrl:'https://youtu.be/TcMBFSGVi1c?si=Ez6PXzNR8SHPLDSV',
    videoUrl1:'https://youtu.be/CDgy_Dn92LE?si=jgwVbngxk4roqAph',
    videoUrl2:'https://youtu.be/GOoysyPkG28?si=zEddkdf6adrvrd6q',
    videoUrl3:'https://youtu.be/KpZZGtDk4YU?si=ZJxGmej7VWgGHU6j',   
     videoUrl4:'https://youtu.be/9x2Bvn0CFoQ?si=9QTUGKHh3hAVCNjr',
      videoUrl5:'https://youtu.be/4iQbD8_YAuA?si=dSNR9HCkoIOwtulv',
      ott:"https://www.hotstar.com/in/movies/vikram/1260106598?search_query=vikra",
  director: 'Anthony and Joe Russo',
  cast: [
    { id: 1, name: 'Robert Downey Jr.' },
    { id: 2, name: 'Chris Evans' }
  ],
  directors: [{ id: 1, name: 'Anthony Russo' }, { id: 2, name: 'Joe Russo' }],
  genres: [{ id: 1, name: 'Superhero' }, { id: 2, name: 'Sci-Fi' }],
  rating: '8.4',
  releaseDate: '2019-04-26',
  runtime: 181,
  popularity: 99.9,
  votes: 2500000,
  revenue: '$2.798B',
  budget: '$356M',
  homepage: 'https://www.marvel.com/movies/avengers-endgame'
},
{
  id: 11,
  name: 'Good Bad Ugly',
  image: 'https://resizing.flixster.com/r4uXNyPr6IkIgkL-0uux7AW2eoE=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzL2IyMWRhNTgxLWM5ZDEtNGIzZi1hNjBjLTI1OTk0OGY2MmQ4Mi5qcGc=',
  description: 'A retired gangster returns to his violent ways after his son is wrongfully convicted, battle against old enemies.',
   videoUrl:'https://youtu.be/c9zWcnNR2q0?si=ph1aOKrD_CiGwL_U',
    videoUrl1:'https://youtu.be/5_pNYak1_Tg?si=O-hO19aX7gzy6W_J',
    videoUrl2:'https://youtu.be/0z2bwlJvPbo?si=hRvl6OKKP9Lpve4b',
    videoUrl3:'https://youtu.be/5g6hWonqXr8?si=vvic9q5hAdX19hJZ',   
     videoUrl4:'https://youtu.be/auyA6GVHbbI?si=i7h7KCjiIWQp87ah',
      videoUrl5:'https://youtu.be/fcSBAVU49xY?si=lk5_sABJI2ApFzPq',
      ott:"https://www.hotstar.com/in/movies/vikram/1260106598?search_query=vikra",
  director: 'Adhik Ravichandran',
  cast: [
    { id: 1, name: 'Ajith Kumar' },
    { id: 2, name: 'Trisha Krishnan' }
  ],
  directors: [{ id: 1, name: 'Adhik Ravichandran' }],
  genres: [{ id: 1, name: 'Action' }, { id: 2, name: 'Comedy' }],
  rating: '5.6',
  releaseDate: '2025-04-10',
  runtime: 139,
  popularity: 92.1,
  votes: 12000,
  revenue: '₹179–300 crore',
  budget: '₹270–300 crore',
  homepage: 'https://www.imdb.com/title/tt27540217/'
},
{
  id: 12,
  name: 'Karuppu',
  image: 'https://cdn.digitalreleasedates.com/movies/11455/posters/4KZXlZ5tTT6ghbW77gS4hSLkCd7.webp',
  description: 'A gripping action drama where a man confronts his past and fights for justice in a corrupt system.',
  director: 'RJ Balaji',
  videoUrl:'https://youtu.be/Llss1aRo8tw?si=26xv6qtKRBHkwLQU',
  cast: [
    { id: 1, name: 'Suriya' },
    { id: 2, name: 'Trisha Krishnan' }
  ],
  directors: [{ id: 1, name: 'RJ Balaji' }],
  genres: [{ id: 1, name: 'Action' }, { id: 2, name: 'Drama' }],
  rating: '9.0',
  releaseDate: '2025-12-20',
  runtime: 145,
  popularity: 90.5,
  votes: 8000,
  revenue: '₹200 crore',
  budget: '₹100 crore',
  homepage: 'https://www.imdb.com/title/tt33988385/'
},
{
  id: 13,
  name: 'Spider-Man: Across the Spider-Verse',
  image: 'https://comicbook.com/wp-content/uploads/sites/4/2023/06/2f68ceb4-c6e7-463f-9206-1726714fcb87.jpg',
  description: 'Miles Morales journeys across the multiverse.',
  director: 'Joaquim Dos Santos, Kemp Powers, Justin K. Thompson',
  videoUrl: 'https://youtu.be/cqGjhVJWtEg?si=QERJtwQyps1ytoSl',
  cast: [
    { id: 1, name: 'Shameik Moore' },
    { id: 2, name: 'Hailee Steinfeld' },
    { id: 3, name: 'Oscar Isaac' }
  ],
  directors: [
    { id: 1, name: 'Joaquim Dos Santos' },
    { id: 2, name: 'Kemp Powers' },
    { id: 3, name: 'Justin K. Thompson' }
  ],
  genres: [{ id: 1, name: 'Animation' }, { id: 2, name: 'Action' }, { id: 3, name: 'Adventure' }],
  rating: '8.5',
  releaseDate: '2023-06-02',
  runtime: 140,
  popularity: 95.2,
  votes: 473000,
  revenue: '$690.8 million',
  budget: '$150 million',
  homepage: 'https://www.imdb.com/title/tt9362722/'
},
{
  id: 14,
  name: 'The Monkey King',
  image: 'https://tse1.mm.bing.net/th/id/OIP.5Z_f9C7j88rLLtNHJJIfTAHaK-?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
  description: 'A rebellious monkey battles demons, dragons, and gods in a journey of self-discovery and cosmic mischief.',
  director: 'Anthony Stacchi',
  videoUrl: 'https://youtu.be/-Ao79QJNE-s?si=tiqDEXR1l9btD2i5',
  cast: [
    { id: 1, name: 'Jimmy O. Yang' },
    { id: 2, name: 'Bowen Yang' },
    { id: 3, name: 'BD Wong' }
  ],
  directors: [{ id: 1, name: 'Anthony Stacchi' }],
  genres: [{ id: 1, name: 'Animation' }, { id: 2, name: 'Comedy' }, { id: 3, name: 'Fantasy' }],
  rating: '7.0',
  releaseDate: '2023-08-18',
  runtime: 92,
  popularity: 88.4,
  votes: 7500,
  revenue: 'N/A',
  budget: 'N/A',
  homepage: 'https://www.imdb.com/title/tt13815990/'
},
{
  id: 15,
  name: 'Elemental',
  image: 'https://lumiere-a.akamaihd.net/v1/images/p_disney_elemental_homeent_v1_2292_0312c1d7.jpeg?region=0,0,540,810',
  description: 'In a city where fire, water, earth, and air residents coexist, Ember and Wade discover how much they have in common.',
  director: 'Peter Sohn',
  videoUrl: 'https://youtu.be/hXzcyx9V0xw?si=JOwsV82AcCVAe-yk',
  cast: [
    { id: 1, name: 'Leah Lewis' },
    { id: 2, name: 'Mamoudou Athie' }
  ],
  directors: [{ id: 1, name: 'Peter Sohn' }],
  genres: [{ id: 1, name: 'Animation' }, { id: 2, name: 'Romance' }, { id: 3, name: 'Fantasy' }],
  rating: '7.0',
  releaseDate: '2023-06-16',
  runtime: 101,
  popularity: 84.7,
  votes: 154000,
  revenue: '$500 million',
  budget: '$200 million',
  homepage: 'https://www.imdb.com/title/tt15789038/'
},
{
  id: 16,
  name: 'TMNT: Mutant Mayhem',
  image: 'https://mlpnk72yciwc.i.optimole.com/cqhiHLc.IIZS~2ef73/w:auto/h:auto/q:75/https://bleedingcool.com/wp-content/uploads/2023/08/TeenageMutantNinjaTurtlesMutantMayhem_EN_800x12001.jpg',
  description: 'The Turtle brothers set out to win the hearts of New Yorkers while facing a mutant army.',
  director: 'Jeff Rowe, Kyler Spears',
  videoUrl: 'https://youtu.be/IHvzw4Ibuho?si=WQrK5INByjYnKC5m',
  cast: [
    { id: 1, name: 'Micah Abbey' },
    { id: 2, name: 'Shamon Brown Jr.' },
    { id: 3, name: 'Nicolas Cantu' }
  ],
  directors: [
    { id: 1, name: 'Jeff Rowe' },
    { id: 2, name: 'Kyler Spears' }
  ],
  genres: [{ id: 1, name: 'Animation' }, { id: 2, name: 'Action' }, { id: 3, name: 'Comedy' }],
  rating: '7.2',
  releaseDate: '2023-08-02',
  runtime: 99,
  popularity: 89.1,
  votes: 75000,
  revenue: '$180 million',
  budget: '$70 million',
  homepage: 'https://www.imdb.com/title/tt8589698/'
},
{
  id: 17,
  name: 'Mufasa: The Lion King',
  image: 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/16b34b32-4456-4497-8744-861a161193fd/dhkeks0-4bd31fcf-c2b8-48bc-b036-f475830ea9f3.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzE2YjM0YjMyLTQ0NTYtNDQ5Ny04NzQ0LTg2MWExNjExOTNmZFwvZGhrZWtzMC00YmQzMWZjZi1jMmI4LTQ4YmMtYjAzNi1mNDc1ODMwZWE5ZjMuanBnIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.jvQIxbayNO6L19nAGyiVspZ7HslbIGTkWTl1HX3gEYA',
  description: 'Rafiki recounts the legend of Mufasa’s rise from orphaned cub to king, revealing a tale of friendship, destiny, and courage.',
  director: 'Barry Jenkins',
  videoUrl: 'https://youtu.be/o17MF9vnabg?si=2CpmIjLiHLLMWFDB',
  cast: [
    { id: 1, name: 'Aaron Pierre' },
    { id: 2, name: 'Kelvin Harrison Jr.' },
    { id: 3, name: 'Tiffany Boone' }
  ],
  directors: [{ id: 1, name: 'Barry Jenkins' }],
  genres: [{ id: 1, name: 'Animation' }, { id: 2, name: 'Musical' }, { id: 3, name: 'Family' }],
  rating: '7.8',
  releaseDate: '2025-02-21',
  runtime: 118,
  popularity: 91.4,
  votes: 98000,
  revenue: '$620 million',
  budget: '$250 million',
  homepage: 'https://www.imdb.com/title/tt13287846/'
},
{
  id: 18,
  name: 'Kung Fu Panda 4',
  image: 'https://www.dreamworks.com/storage/cms-uploads/kung-fu-panda-4-he-poster.jpg',
  description: 'Po is chosen as the Spiritual Leader of the Valley of Peace and must find and train a new Dragon Warrior while facing a new threat.',
  director: 'Mike Mitchell, Stephanie Stine',
  videoUrl: 'https://youtu.be/_inKs4eeHiI?si=c1bF0j8Vh-THmaaC',
  cast: [
    { id: 1, name: 'Jack Black' },
    { id: 2, name: 'Awkwafina' },
    { id: 3, name: 'Viola Davis' }
  ],
  directors: [
    { id: 1, name: 'Mike Mitchell' },
    { id: 2, name: 'Stephanie Stine' }
  ],
  genres: [{ id: 1, name: 'Animation' }, { id: 2, name: 'Action' }, { id: 3, name: 'Comedy' }],
  rating: '6.3',
  releaseDate: '2024-03-08',
  runtime: 94,
  popularity: 87.9,
  votes: 72000,
  revenue: '$390 million',
  budget: '$130 million',
  homepage: 'https://www.imdb.com/title/tt23833708/'
},
{
  id: 19,
  name: 'The Wild Robot',
  image: 'https://mlpnk72yciwc.i.optimole.com/cqhiHLc.IIZS~2ef73/w:auto/h:auto/q:75/https://bleedingcool.com/wp-content/uploads/2024/06/WRB_Tree1Sheet6_RGB_1.jpg',
  description: 'Roz, a robot shipwrecked on a remote island, learns to live among animals and raise a baby goose.',
  director: 'Chris Sanders',
  videoUrl: 'https://youtu.be/67vbA5ZJdKQ?si=GLJP4JTwZZaZNkDO',
  cast: [
    { id: 1, name: 'Lupita Nyong\'o' },
    { id: 2, name: 'Pedro Pascal' },
    { id: 3, name: 'Kit Connor' }
  ],
  directors: [{ id: 1, name: 'Chris Sanders' }],
  genres: [{ id: 1, name: 'Animation' }, { id: 2, name: 'Adventure' }, { id: 3, name: 'Family' }],
  rating: '8.2',
  releaseDate: '2024-09-20',
  runtime: 102,
  popularity: 93.6,
  votes: 192000,
  revenue: '$470 million',
  budget: '$120 million',
  homepage: 'https://www.imdb.com/title/tt14545470/'
},
{
  id: 20,
  name: 'KPop Demon Hunters',
  image: 'https://image.tmdb.org/t/p/original/jfS5KEfiwsS35ieZvdUdJKkwLlZ.jpg',
  description: 'A world-famous K-Pop group balances fame and fashion with their secret lives as demon hunters.',
  director: 'Chris Appelhans, Maggie Kang',
  videoUrl: 'https://youtu.be/3JTVQTk36R8?si=I7_bVkm1scvvCMzM',
  cast: [
    { id: 1, name: 'Arden Cho' },
    { id: 2, name: 'May Hong' },
    { id: 3, name: 'Ji-young Yoo' }
  ],
  directors: [
    { id: 1, name: 'Chris Appelhans' },
    { id: 2, name: 'Maggie Kang' }
  ],
  genres: [{ id: 1, name: 'Animation' }, { id: 2, name: 'Musical' }, { id: 3, name: 'Fantasy' }],
  rating: '7.7',
  releaseDate: '2025-06-20',
  runtime: 95,
  popularity: 90.8,
  votes: 46000,
  revenue: 'TBA',
  budget: 'TBA',
  homepage: 'https://www.imdb.com/title/tt21936664/'
},
{
  id: 21,
  name: 'The Witcher: Sirens of the Deep',
  image: 'https://tse1.mm.bing.net/th/id/OIP.7UR6tJyL01k3ukyT_N8tNQHaLH?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
  description: 'Geralt of Rivia must stop a war between humans and merpeople after mysterious attacks threaten coastal villages.',
  director: 'Kang Hei Chul',
  videoUrl: 'https://youtu.be/PYzqa1CDTik?si=EMtDy1OZEG2aGxKn',
  cast: [
    { id: 1, name: 'Doug Cockle' },
    { id: 2, name: 'Joey Batey' },
    { id: 3, name: 'Emily Carey' }
  ],
  directors: [{ id: 1, name: 'Kang Hei Chul' }],
  genres: [{ id: 1, name: 'Animation' }, { id: 2, name: 'Fantasy' }, { id: 3, name: 'Action' }],
  rating: '6.1',
  releaseDate: '2025-02-11',
  runtime: 91,
  popularity: 82.4,
  votes: 9500,
  revenue: 'TBA',
  budget: 'TBA',
  homepage: 'https://www.imdb.com/title/tt27871614/'
},
{
    id: 22,
    name: "Thudarum",
    image: "https://image.tmdb.org/t/p/original/kSocElJdVBlSUWvoIClYezVqMxQ.jpg",
    description: "Mohanlal stars in a gripping action thriller that became a massive hit.",
    directors: [{ id: 1, name: 'Tharun Moorthy' }],
    videoUrl: "https://youtu.be/83Mc7EhifCk",
    cast: [
      { id: 1, name: "Mohanlal" },
      { id: 2, name: "Shobana" }
    ],
    genres: [{ id: 1, name: 'Action' }, { id: 2, name: 'Thirller' }],
    rating: "7.6",
    releaseDate: "2025-04-25",
    runtime: 166,
    popularity: null,
    votes: null,
    revenue: "₹230–235 crore worldwide",
    budget: "10 crore",
    homepage: ""
  },
  {
    id: 23,
    name: "Paradha",
    image: "https://assets-in.bmscdn.com/iedb/movies/images/mobile/thumbnail/xlarge/paradha-et00398438-1752837627.jpg",
    description: "A women-centric social drama celebrating female friendships.",
    directors: [{ id: 1, name: '	Praveen Kandregula' }],
    videoUrl: "https://youtu.be/CfOVSlagCg8?si=cTz18xj4RTfHcBQf",
    cast: [
      { id: 1, name: "Anupama Parameswaran" }
    ],
    genres: [{ id: 1, name: "Drama" }],
    rating: "",
    releaseDate: "2025-08-22",
    runtime: null,
    popularity: null,
    votes: null,
    revenue: "",
    budget: "",
    homepage: ""
  },
  {
    id: 24,
    name: "Kaliyugam / Kaliyugam 2064",
    image: "https://upload.wikimedia.org/wikipedia/en/9/98/Kaliyugam_%282025_film%29.jpg",
    description: "A post-apocalyptic psychological thriller shot in Tamil and Telugu.",
    directors: [{ id: 1, name: 'Pramodh Sundar' }],
    videoUrl: "https://youtu.be/-rFIQTutUzo?si=NznR9K6n_s5PhBIs",
    cast: [
      { id: 1, name: "Shraddha Srinath" },
      { id: 2, name: "Kishore" }
    ],
    genres: [{ id: 1, name: "Thriller" }, { id: 2, name: "Psychological" }],
    rating: "",
    releaseDate: "2025-05-09",
    runtime: 111,
    popularity: null,
    votes: null,
    revenue: "",
    budget: "",
    homepage: ""
  },
  {
    id: 25,
    name: "Mahavatar Narsimha",
    image: "https://tamilyogi.up.in/wp-content/uploads/2025/01/tsTC69zbKSloEEVD9FUS3robmyh.jpg",
    description: "Mythological fantasy saga released in multiple languages, including Tamil, Telugu, Malayalam.",
    directors: [{ id: 1, name: '	Praveen Kandregula' }],
    videoUrl: "https://youtu.be/_bZpa_8lz4w?si=22kREGa6uJd0f91M",
    cast: [],
    genres: [{ id: 1, name: "Fantasy" }, { id: 2, name: "Drama" }],
    rating: "",
    releaseDate: "2025-07-25",
    runtime: 131,
    popularity: null,
    votes: null,
    revenue: "",
    budget: "",
    homepage: ""
  },
  {
    id: 26,
    name: "Game Changer",
    image: "https://m.media-amazon.com/images/M/MV5BM2IxOGRlZTQtYzRlOS00ZDNjLTkxYmEtNDk4ZTI2NWFlYjZhXkEyXkFqcGc@._V1_.jpg",
    description: "Political thriller starring Ram Charan as an honest IAS officer.",
    directors: [{ id: 1, name: 'S. Shankar' }],
    videoUrl: "https://youtu.be/CXBLDC2WGbk?si=WKaoOjuzB5U_YBeg",
    cast: [
      { id: 1, name: "Ram Charan" },
      { id: 2, name: "Kiara Advani" }
    ],
    genres: [{ id: 1, name: "Political" }, { id: 2, name: "Thriller" }],
    rating: "",
    releaseDate: "2025-01-10",
    runtime: null,
    popularity: null,
    votes: null,
    revenue: "",
    budget: "",
    homepage: ""
  },
  {
    id: 27,
    name: "Thug Life",
    image: "https://media5.bollywoodhungama.in/wp-content/uploads/2024/11/Thug-Life.jpeg",
    description: "Kamal Haasan re-teams with Mani Ratnam for a gripping action saga.",
    directors:[{ id: 1, name: "Mani Ratnam" }] ,
    videoUrl: "https://youtu.be/96kAbj3IF3k?si=bcQ4mlZEIyj7dFFT",
    cast: [{ id: 1, name: "Kamal Haasan" }],
    genres: [{ id: 1, name: "Action" }],
    rating: "",
    releaseDate: "2025-06",
    runtime: null,
    popularity: null,
    votes: null,
    revenue: "",
    budget: "",
    homepage: ""
  },
  {
    id: 28,
    name: "L2: Empuraan",
    image: "https://stat4.bollywoodhungama.in/wp-content/uploads/2024/05/L2E-Empuraan-2.jpg",
    description: "Sequel to Lucifer, with Mohanlal reprising his powerful role.",
    directors: [{ id: 1, name: "Prithviraj Sukumaran" }] ,
    videoUrl: "https://youtu.be/-ERYOeh3PO0?si=8uc-gnvvYdewHESa",
    cast: [
      { id: 1, name: "Mohanlal" },
      { id: 2, name: "Manju Warrier" }
    ],
    genres: [{ id: 1, name: "Action" }, { id: 2, name: "Drama" }],
    rating: "",
    releaseDate: "2025",
    runtime: null,
    popularity: null,
    votes: null,
    revenue: "",
    budget: "",
    homepage: ""
  },
  
  {
    id: 29,
    name: "Dude",
    image: "https://static.moviecrow.com/gallery/20250511/246272-dude.jpeg",
    description: "A youthful entertainer with comedy, friendship, and emotions.",
    directors: [{ id: 1, name: "Keerthiswaran" }],
    videoUrl: "https://youtu.be/4Bsc2uI_LsM?si=JJ6Qt6FJyJQUXiNT",
    cast: [
      { id: 1, name: "Pradeep Ranganathan" },
      { id: 2, name: "Mamitha Baiji" }
    ],
    genres: [{ id: 1, name: "Comedy" }, { id: 2, name: "Drama" }],
    rating: "",
    releaseDate: "2025",
    runtime: null,
    popularity: null,
    votes: null,
    revenue: "",
    budget: "",
    homepage: ""
  },
  {
    id: 30,
    name: "OG",
    image: "https://images.filmibeat.com/img/popcorn/movie_posters/og---original-gangsters-20230904105927-21436.jpg",
    description: "Powerful gangster drama starring Pawan Kalyan.",
    directors: [{ id: 1, name: "Sujeeth" }],
    videoUrl: "https://youtu.be/ePOglweqy7o?si=9PPYFkXnUrKUGZxS",
    cast: [
      { id: 1, name: "Pawan Kalyan" },
      { id: 2, name: "Emraan Hashmi" },
      { id: 3, name: "Priyanka Mohan" }
    ],
    genres: [{ id: 1, name: "Action" }, { id: 2, name: "Thriller" }],
    rating: "",
    releaseDate: "2025",
    runtime: null,
    popularity: null,
    votes: null,
    revenue: "",
    budget: "",
    homepage: ""
  },
  {
    id: 31,
    name: "Madharaasi",
    image: "https://m.media-amazon.com/images/M/MV5BYjQ4NmU4YzQtMWNiYi00ZDA3LTk0YmEtMTBkZGVkZTJlNjRiXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    description: "A psychological action thriller by A. R. Murugadoss starring Sivakarthikeyan, Rukmini Vasanth, Vidyut Jammwal, Biju Menon.",
    directors: [{ id: 1, name: "A. R. Murugadoss" }],
    videoUrl: "https://youtu.be/Hgw4S7SDo3U?si=EIH5u8tLI-xjB5Vi",
    cast: [
      { id: 1, name: "Sivakarthikeyan" },
      { id: 2, name: "Rukmini Vasanth" },
      { id: 3, name: "Viduyt Jammwal" }
    ],
    genres: [{ id: 1, name: "Action" }, { id: 2, name: "Thriller" }],
    rating: "",
    releaseDate: "2025-09-05",
    runtime: null,
    popularity: null,
    votes: null,
    revenue: "",
    budget: "₹200 crore",
    homepage: ""
  },
  {
    id: 32,
    name: "Raajsaab",
    image: "https://m.media-amazon.com/images/M/MV5BOWM0YTlmZjEtOTA5ZC00MmY0LTk4NjgtNGUyYjAzZTk3ZmMxXkEyXkFqcGc@._V1_.jpg",
    description: "The plot revolves around a young man, who sets his eyes on his ancestral property to ease him out of a cash crunch.",
    directors: [{ id: 3, name: "Maruthi" }],
    videoUrl: "https://youtu.be/lHy5uu0NxWo?si=75_pwwD-wPFn5tMt",
    cast: [
      { id: 1, name: "Prabhas" },
      { id: 2, name: "Malavika Mohanan" },
      { id: 3, name: "Sanjay Dutt" }
    ],
    genres: [
      { id: 1, name: "paranormal romantic comedy" },
      { id: 2, name: "Entertainment" }
    ],
    rating: "",
    releaseDate: "2025-11-07",
    runtime: null,
    popularity: null,
    votes: null,
    revenue: "",
    budget: "₹300 crore",
    homepage: ""
  },
  {
    id: 33,
    name: "Kantara Chapter 2",
    image: "https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AA1ugtjC.img?w=768&h=1109&m=6",
    description: "A prequel to the blockbuster Kantara, exploring the origins of the divine folklore and the legendary daiva worship traditions.",
    directors: [{ id: 4, name: "Rishab Shetty" }],
    videoUrl: "https://youtu.be/A83aYDaqDOw?si=W_WvnGZ5yvML99Nc",
    cast: [
      { id: 1, name: "Rishab Shetty" },
      { id: 2, name: "Sapthami Gowda" }
    ],
    genres: [
      { id: 1, name: "Drama" },
      { id: 2, name: "Thriller" },
      { id: 3, name: "Fantasy" }
    ],
    rating: "",
    releaseDate: "2025-12-20",
    runtime: null,
    popularity: null,
    votes: null,
    revenue: "",
    budget: "₹250 crore",
    homepage: ""
  },
  {
    id: 34,
    name: "Toxic",
    image: "https://m.media-amazon.com/images/M/MV5BMDZiNzAwZTQtYWIwMC00ODA0LWJiOGMtZTgzZGYzYzMxMDNiXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    description: "A gangster drama set in the 1970s-80s underworld, starring Yash in a stylish and intense role with a retro backdrop.",
    directors: [{ id: 5, name: "Geethu Mohandas" }],
    videoUrl: "https://youtu.be/0PfErHA3zzQ?si=2epXsSUQnDHJkOc9",
    cast: [
      { id: 1, name: "Yash" },
      { id: 2, name: "Kiara Advani" },
      { id: 3, name: "Darrell D Silva" }
    ],
    genres: [
      { id: 1, name: "Action" },
      { id: 2, name: "Crime" },
      { id: 3, name: "Drama" }
    ],
    rating: "",
    releaseDate: "2025-10-23",
    runtime: null,
    popularity: null,
    votes: null,
    revenue: "",
    budget: "₹350 crore",
    homepage: ""
  },
  {
    id: 35,
    name: "Peddi",
    image: "https://images.filmibeat.com/ph-big/2025/03/ram-charan-tejas-upcoming-movie-peddi-first-look-poster-released1743054025_0.jpg",
    description: "Peddi is an upcoming Indian Telugu-language sports action drama film[1][2] written and directed by Buchi Babu Sana and produced by Venkata Satish Kilaru.",
    directors: [{ id: 6, name: "Buchi Babu Sana" }],
    videoUrl: "https://youtu.be/mGrFXawfrd4?si=b8eSZSfWliq8ticc",
    cast: [
      { id: 1, name: "Ram Charan" },
      { id: 2, name: "Janhvi Kapoor" },
      { id: 3, name: "Shivarajkumar" }
    ],
    genres: [{ id: 1, name: "Action" }, { id: 2, name: "Drama" }],
    rating: "",
    releaseDate: "2026-12-25",
    runtime: null,
    popularity: null,
    votes: null,
    revenue: "",
    budget: "₹400 crore",
    homepage: ""
  }






  
  ]
export default Data;
